### ISSUE TITLE
How to measure the similarity between a whole group of images?

### ISSUE THREAD

**Issue by yuriachermann** [richzhang/PerceptualSimilarity#100]
I need to compare the similarity between images inside different groups.
I have 2 different groups with 100 images each and I need to compare the inner similarity of both.
Is there a method inside [PerceptualSimilarity](https://github.com/richzhang/PerceptualSimilarity) for that?

**Comment by richzhang** [comment]
Take a look at this file: https://github.com/richzhang/PerceptualSimilarity/blob/master/lpips_2dirs.py
