### ISSUE TITLE
Code request - self-supervides

### ISSUE THREAD

**Issue by roimehrez** [richzhang/PerceptualSimilarity#11]
Hi,
Any chance you can share the code for split-Brain / BiGAN / Puzzle

Thanks!!

**Comment by richzhang** [comment]
Hi, sorry, I am not planning to do this right now. If you can write a wrapper around the models and compute a distance, then you can plug it into the dataset scoring function like [here](https://github.com/richzhang/PerceptualSimilarity/blob/master/test_dataset_model.py#L42).

Thanks!
