### ISSUE TITLE
torch.device("cuda:0")?

### ISSUE THREAD

**Issue by ford442** [richzhang/PerceptualSimilarity#110]
I have been testing around loading models at float16 via CUDA and by cpu.
Is it best to use map_location=torch.device("cpu")?
Or can we use torch.device("cuda:0")? Was LPIPS trained on cpu making this a situaltion where map_location='cpu' is needed?

Thanks for your input!  :)

**Comment by richzhang** [comment]
The model should load onto cpu by default, and then you should be able to load the model onto any device after
