### ISSUE TITLE
What's the input image size of Alexnet/VGG/Squeezenet?

### ISSUE THREAD

**Issue by coolKeen** [richzhang/PerceptualSimilarity#12]
Nice paper! One question:What's the input image size of Alexnet/VGG/Squeezenet?

Thanks in advance!

**Comment by coolKeen** [comment]
Specifically, I want to know what is the input image size when you train the Alexnet/VGG/Squeezent with linearly "calibrating"  layer?

**Comment by richzhang** [comment]
It's trained on 64x64 patches. But it can be run "fully convolutionally" at
any resolution at test time.

Richard

**Comment by coolKeen** [comment]
Thanks for respond!
