### ISSUE TITLE
how can I wget the JND Dataset, the old URL was unavailable?

### ISSUE THREAD

**Issue by armyw** [richzhang/PerceptualSimilarity#125]
Dear Dr.Zhang,
I hope you're doing well. I am requesting access to the JND Dataset, specifically, the 2AFC Val set and 2AFC Train set, for the GitHub PerceptualSimilarity project.
I have attempted to download the dataset from the GitHub repository, but I encountered an error message stating, “The server has encountered a problem because access is restricted.” I would greatly appreciate it if you could provide me with access to the dataset or assist me in resolving this issue.
Thank you for your attention to this matter. I look forward to hearing from you soon.

**Comment by zhangjiewu** [comment]
Same problem.

**Comment by SaraGhazanfari** [comment]
Hi,
You can find the dataset in the [R-LPIPS](https://github.com/SaraGhazanfari/R-LPIPS) repo.
Please give a star to the project if you find it interesting.
Thanks,
Sara

**Comment by richzhang** [comment]
Yikes, let me look into rehosting it somewhere else. For now the R-LPIPS looks good

**Comment by richzhang** [comment]
Hi, it's rehosted. The scripts [scripts/download_dataset.sh](https://github.com/richzhang/PerceptualSimilarity/blob/master/scripts/download_dataset.sh) and [scripts/download_dataset_valonly.sh](https://github.com/richzhang/PerceptualSimilarity/blob/master/scripts/download_dataset_valonly.sh) are updated. Thanks!
