### ISSUE TITLE
Can be used for 3D data ?

### ISSUE THREAD

**Issue by Arksyd96** [richzhang/PerceptualSimilarity#126]
I'm wondering if this metric can be used to evaluate 3D volumes in a slice-wise fashion, by comparing 2D slices of the same level ! What do you think ?

**Comment by richzhang** [comment]
That's an interesting question. We didn't verify the method for that application. For large distortions, it probably won't work well. For example, if you are just comparing shapes, something like Chamfer distance would be more standard (although may not be perceptual either)

**Comment by Arksyd96** [comment]
I see, well, one can still try testing the method on 3D-vs-2D benchmarks, if there is any correlation between LPIPS scores on 3D and 2D data then it can probably be used as metric on 2D too !
