### ISSUE TITLE
How do I turn off the screen spam?

### ISSUE THREAD

**Issue by DarkAlchy** [richzhang/PerceptualSimilarity#129]
Setting up [LPIPS] perceptual loss: trunk [alex], v[0.1], spatial [off]
Loading model from: F:\strohs\venv\lib\site-packages\lpips\weights\v0.1\alex.pth

That is spit out  each time the pbar updates with the mean loss.

**Comment by richzhang** [comment]
Make sure you're only setting up the loss object once, for example `loss_fn = lpips.LPIPS(net='alex')`. Not everytime the loss is being computed

You can also turn verbose=False https://github.com/richzhang/PerceptualSimilarity/blob/master/lpips/lpips.py#L61
