### ISSUE TITLE
suggested fix in weights loading code

### ISSUE THREAD

**Issue by robertmash2** [richzhang/PerceptualSimilarity#14]
I find that when I import PerceptualSimilarity as a package, the weights loading line in dist_model.py fails as '.' points to the current directory of my calling code rather than the root directory of PerceptualSimilarity.

Here's a patch that fixes the issue:
[fix_ps.patch.txt](https://github.com/richzhang/PerceptualSimilarity/files/2221140/fix_ps.patch.txt)

**Comment by richzhang** [comment]
I made the corresponding change. Thanks a lot!
