### ISSUE TITLE
Geometric distortion

### ISSUE THREAD

**Issue by nikky4D** [richzhang/PerceptualSimilarity#15]
Is it possible to use this to measure geometric distortion? As in the quality of a retargeting compared to a full reference?

**Comment by richzhang** [comment]
Our dataset had geometric distortions, and deep features outperformed traditional metrics.

**Comment by nikky4D** [comment]
Thank you. Do you have an example I can look at? I would like to compare against metrics for measuring retargeting success such as amount of geometric distortion introduced and information loss. Typical SSIM, L2, L1 losses have not been used for these purposes.

**Comment by richzhang** [comment]
Great. Unfortunately, I don't have specific examples with just geometric distortions.
