### ISSUE TITLE
Performance on ImageNet data (and similarly sized images)

### ISSUE THREAD

**Issue by seansaito** [richzhang/PerceptualSimilarity#16]
I notice that the model by default assumes images of dimensions 64x64. I'm curious how the model/distance metric performs for higher resolutions like that of ImageNet (224x224).

**Comment by richzhang** [comment]
The model is fully-convolutional, so it can be run at any resolution. All our empirical tests are on 64x64 though.

**Comment by seansaito** [comment]
Thanks for the reply! I see, any intuitions on how well it would work on 224x224 data?

**Comment by richzhang** [comment]
The edge effects will be slightly different, but it should work okay.
