### ISSUE TITLE
data normalization - possible bug

### ISSUE THREAD

**Issue by rosenfeldamir** [richzhang/PerceptualSimilarity#20]
I noticed that the data normalization is 
```
transforms.Normalize((0.5, 0.5, 0.5),(0.5, 0.5, 0.5))
```
(for example in twoafc_dataset.py). 
The imagenet normalization coefficients are 
mean=[0.485, 0.456, 0.406],
std=[0.229, 0.224, 0.225]
This raises the questions:
1. possibly you confused mean with variance? (the Normalize function accepts std as the second argument, not variance)
2. any reason behind the design choice not to use the imagenet normalization?

**Comment by richzhang** [comment]
This "normalize" converts images from [0,1] to [-1,+1]. We do the actual imagenet normalization here: https://github.com/richzhang/PerceptualSimilarity/blob/master/models/networks_basic.py#L112

**Comment by zakajd** [comment]
Hi
I don't understand where did you get the normalization values.
Currently your using `mean = [ -.030,-.088,-.188]` and `std = [.458,.448,.450]` which doesn't correspond to ImageNet statistics.
        self.register_buffer('shift', torch.Tensor([-.030,-.088,-.188])[None,:,None,None])
        self.register_buffer('scale', torch.Tensor([.458,.448,.450])[None,:,None,None])

**Comment by richzhang** [comment]
Thanks for the question. The imagenet statistics assume images are normalized between [0,1]. This code uses images from [-1,+1], so the appropriate transformation is done (notice that the std is just doubled)

**Comment by zakajd** [comment]
Thank you for the fast answer =)
