### ISSUE TITLE
Using LPIPS metric for image retrieval

### ISSUE THREAD

**Issue by woctezuma** [richzhang/PerceptualSimilarity#22]
I understand that the model takes as input two images, by design. I would like to know if there is a smart way to use LPIPS metric for image retrieval, other than computing all the pairwise distances.

For information, my dataset of [game banners](https://github.com/woctezuma/download-steam-banners) contains about 30k images. In my previous experiments, I extracted image features **once**, and could then work with this processed data using standard tools for efficient similarity search based on cosine similarity, Minkowski distance, etc.

Thank your for your attention.

**Comment by richzhang** [comment]
You could save off all the intermediate features (scaled by the learned linear weights), and then use this embedding for retrieval, but it will be very memory expensive. Finding a low-dimensional embedding, consistent with LPIPS distance, would be useful research for this application.
