### ISSUE TITLE
does the lpips work on grey images?

### ISSUE THREAD

**Issue by agniszczotka** [richzhang/PerceptualSimilarity#23]
Is this safe to use lpips for gray images? The code does not work for 1 channel images. The hack would be to use 3 identical channels yet I am not sure what would be the effect within the end-to-end calibrated solution on color images.

**Comment by richzhang** [comment]
I didn't test specifically on grayscale images, but it should still give some notion of distance.

**Comment by agniszczotka** [comment]
thank you for the update

**Comment by Aniket1998** [comment]
Facing the same issue myself. Need to use LPIPS (averaged over the number of frames) as a metric of Perceptual Similarity for the KTH Action Video Dataset (which is grayscale). Is replicating the single channels to 3 identical channels an acceptable way to obtain a similarity measure? Does there exist a better alternative?

**Comment by richzhang** [comment]
The most proper (but perhaps time-consuming) thing would be to retrain AlexNet to do ImageNet classification on grayscale images. This would be a 1-line change to [this](https://github.com/pytorch/examples/tree/master/imagenet) codebase (add a line in the data loader to force images to be grayscale). Then do a linear calibration steps with our perceptual judgments from the BAPPS dataset.

Replicating to 3 identical channels is a reasonable alternative.
