### ISSUE TITLE
When I use compute_dists.py and get the distance between 2 images, what does it mean?

### ISSUE THREAD

**Issue by AdarshMJ** [richzhang/PerceptualSimilarity#24]
If the distance is smaller, does it mean the two images are similar?

**Comment by richzhang** [comment]
Yup!

**Comment by AdarshMJ** [comment]
Oh okay. Cool got it. Thank you for clarifying this.
Also you mention to calculate the distance between two image patches we first compute deep embeddings. What exactly does it mean? Do you extract features?

**Comment by richzhang** [comment]
Yes, exactly. The AlexNet or VGG features are high-dimensional "embedding" of the image.
