### ISSUE TITLE
Hello， Is the distance of two picture between 0 and 1? 

### ISSUE THREAD

**Issue by cyjxuanwu** [richzhang/PerceptualSimilarity#27]

**Comment by richzhang** [comment]
The minimum is 0: if the two images exactly the same, they will have the same deep activation values and distance will be 0. The max isn't set to anything.

**Comment by cyjxuanwu** [comment]
> 
> 
> The minimum is 0: if the two images exactly the same, they will have the same deep activation values and distance will be 0. The max isn't set to anything.

 Thank you for your reply.
