### ISSUE TITLE
No compute_dists_pair.py

### ISSUE THREAD

**Issue by EndyWon** [richzhang/PerceptualSimilarity#28]
Hello, i can't find the file compute_dists_pair.py, could you release it? Thanks.

**Comment by richzhang** [comment]
Thanks for noticing this! Just added it.

**Comment by EndyWon** [comment]
Thanks for sharing this. I wanna to know if the dir contains n pictures, could this code compare all pairs (i.e., n(n-1)/2 pairs) of these pictures? This is very important to infer the number of pairs.

**Comment by richzhang** [comment]
It should. It will spit out all pair of image files that it's running on.
