### ISSUE TITLE
for the appendix of paper

### ISSUE THREAD

**Issue by Xiaotong713986** [richzhang/PerceptualSimilarity#32]
Hi, I can't find the appendix of your paper. Could you help me find it?

**Comment by richzhang** [comment]
It starts on page 10 in the arxiv: https://arxiv.org/abs/1801.03924

**Comment by Xiaotong713986** [comment]
Thank you very much!




------------------ 原始邮件 ------------------
发件人: "Richard Zhang"<notifications@github.com>;
发送时间: 2019年8月26日(星期一) 中午11:29
收件人: "richzhang/PerceptualSimilarity"<PerceptualSimilarity@noreply.github.com>;
抄送: "肖晓彤"<810011624@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [richzhang/PerceptualSimilarity] for the appendix of paper (#32)




It starts on page 10 in the arxiv: https://arxiv.org/abs/1801.03924
