### ISSUE TITLE
Installation on Ubuntu 19.04

### ISSUE THREAD

**Issue by kunguz** [richzhang/PerceptualSimilarity#33]
Thank you for such a well setup! I managed to run the code with a tiny modification on an Ubuntu 19.04. I commented those two lines in your `requirements.txt`:

    #numpy>=1.14.3
    #opencv>=2.4.11

Later, I installed the numpy and the opencv from Ubuntu's own repositories:

    sudo apt-get install python-numpy python-opencv

Lastly, I verified by running comparison of two sample images as in below:

> XXXXX:PerceptualSimilarity$ python compute_dists.py -p0 imgs/ex_ref.png -p1 imgs/ex_p0.png --use_gpu
> Setting up Perceptual loss...
> Loading model from: /home/XXXXX/PerceptualSimilarity/models/weights/v0.1/alex.pth
> ...[net-lin [alex]] initialized
> ...Done
> Distance: 0.722

**Comment by richzhang** [comment]
Thanks for the information!!
