### ISSUE TITLE
Using WGAN to Calculate PerceptualSimilarity

### ISSUE THREAD

**Issue by akhilkatpally** [richzhang/PerceptualSimilarity#34]
Thanks for Publishing the code and appreciate if you could help me understand this. 

I trained a WGAN on my own data. Now, i am planning to use the generator network features[weights] to calculate PerceptualSimilarity score. I am not quite sure how to do this.

If i correctly understood, In either VGG/Resnet we will be passing the query images(image1, image2) through the network, for each input image we get all the features and calculate the score using them. 

But i am not sure how to use that features for WGAN, since the input to the generator network is noise and the output is the synthetically generated images. How do i pass query images to get those features?

**Comment by akhilkatpally** [comment]
I guess i found the answer, WGAN doesn't have the encoder which is present in the BiGAN(which you used) . It was silly that i misread BiGAN as BigGAN. Anyways i found this paper where they are inverting the Generator network of GAN. 
https://arxiv.org/pdf/1802.05701.pdf

**Comment by richzhang** [comment]
Great! Yes, you need an encoder or some network that takes image as input.
