### ISSUE TITLE
There is a bug when I try to train with Multi-GPU.

### ISSUE THREAD

**Issue by mehameha998** [richzhang/PerceptualSimilarity#35]
I guess there is a bug when you put your model to mutil-gpus.  

Reference:
https://github.com/pytorch/pytorch/issues/8637#issuecomment-398268602

**Comment by mehameha998** [comment]
To solve it, using nn.ModuleList() to warp self.lins in model/network_basics.py.

**Comment by LucaSoato** [comment]
Can you tell me a little bit more of your solution? 😃 
Sadly I'm stuck there while trying to train on multiple gpus for camvid segmentation.
