### ISSUE TITLE
How to interpret the distance? 

### ISSUE THREAD

**Issue by yqtianust** [richzhang/PerceptualSimilarity#38]
Hi, how can we interpret the physical meaning of the similarity distance? 
For example in which range, the distance means the images are very similar? 
For example in which range, the distance means the images are very different? 

I understood that 0 means two pictures are exactly the same. However, what if a value is around 0.5? 
Any suggestions? 

Thanks.

**Comment by richzhang** [comment]
Hi, I don't know if the absolute distance has such a clean interpretation, since it's dependent on the input content as well. I use this to compare algorithms to each other

**Comment by saisubramaniam147** [comment]
Can you clarify by 'dependent on input content'? If I were to compare against image generations, how can I use it?

**Comment by richzhang** [comment]
The metric is trained so that the relative values of `d(a, a')` and `d(a, a'')` hopefully consistent

Given different images, such as `d(a, a')` and `d(b, b')`, the values may be similar but may look closer or further, depending on what `a` and `b` are.

**Comment by yuyilin115** [comment]
I met the similar question. 
I  want to use if  d(a, a'') - d(a, a') < 0.01 to show a'' is similar to a'，is this feasible？or Is it feasible to b‘’ and b‘

> The metric is trained so that the relative values of `d(a, a')` and `d(a, a'')` hopefully consistent
> 
> Given different images, such as `d(a, a')` and `d(b, b')`, the values may be similar but may look closer or further, depending on what `a` and `b` are.
