### ISSUE TITLE
Tensor Size Mismatch when running inference for own images

### ISSUE THREAD

**Issue by just-an-anonymous-github-account** [richzhang/PerceptualSimilarity#41]
First of all - great paper!

I'm trying to run the single image similarity script and running into this error (for my own input images of size (224,224,3):

RuntimeError: The size of tensor a (255) must match the size of tensor b (55) at non-singleton dimension 3

Any ideas why this could be happening?

Thanks,

**Comment by dolhasz** [comment]
Apologies - you can ignore this - fixed it.
