### ISSUE TITLE
Can't import models

### ISSUE THREAD

**Issue by bakirillov** [richzhang/PerceptualSimilarity#43]
Hello!

The following doesn't work:
`import PerceptualSimilarity.models as psm`
I have cloned the repository into my working directory and attempt to use the similarity function for my pictures. 
The import fails with the following error:
`ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-6-460708e98c0d> in <module>
----> 1 import PerceptualSimilarity.models as psm

~/HDD/works/Skoltech/CapsuleAD/src/PerceptualSimilarity/models/__init__.py in <module>
      9 from torch.autograd import Variable
     10 
---> 11 from models import dist_model
     12 

ModuleNotFoundError: No module named 'models'`

What am I doing wrong?
Could you please look into it?

**Comment by richzhang** [comment]
Hi, I refactored the code. You should be able to do a `pip install lpips` now!

**Comment by mohit291298** [comment]
I am still getting the same error:
raceback (most recent call last):
  File "scripts/evaluate_changes_clevr.py", line 37, in <module>
    from PerceptualSimilarity import models
  File "/home/cse/dual/cs5160433/simsg/PerceptualSimilarity/models/__init__.py", line 11, in <module>
    from models import dist_model
ModuleNotFoundError: No module named 'models'

And also in import models as utils
Please give a fix
