### ISSUE TITLE
PerceptualLoss uses memory on GPU 0 when specified otherwise

### ISSUE THREAD

**Issue by FeliMe** [richzhang/PerceptualSimilarity#44]
When running PerceptualLoss on a machine with multiple GPUs, it always uses some memory of GPU 0, even when gpu_ids specifies another one.

Minimal example to reproduce:

```
import models
from time import sleep

model = models.PerceptualLoss(model='net-lin', net='vgg', gpu_ids=[2])
sleep(20)
```

<img width="855" alt="Bildschirmfoto 2020-05-08 um 17 10 15" src="https://user-images.githubusercontent.com/24461478/81419716-01fca580-914f-11ea-805c-7254778456fd.png">

**Comment by richzhang** [comment]
Hi, perhaps a quick fix is to do `export CUDA_VISIBLE_DEVICES=2` on the command lind
