### ISSUE TITLE
Compare patches with different spatial resolution

### ISSUE THREAD

**Issue by shivangi-aneja** [richzhang/PerceptualSimilarity#46]
Would it also be possible to compare 2 images with different spatial resolution?
e.g.

img_1 = 256 X 270 X 3
img_2 = 180 X 245 X 3

One hacky way of doing it to resize both images to same size and compare. 
In the end, it network gives a feature vector of different length if image res are different for 2 images. But just curious in case you have tried out something.

**Comment by richzhang** [comment]
Oh, no. They need to be resized. But are the images of the same thing in the first place (have some spatial correspondence)?

**Comment by shivangi-aneja** [comment]
Yeah same but different resolution. So on certain websites you see thumbnail corresponding to articles and when you open the article you see high res image.

**Comment by richzhang** [comment]
Great, resizing seems reasonable then. Keep in mind that many built-in resizing functions do not properly antialias: https://twitter.com/jaakkolehtinen/status/1258102168176951299
