### ISSUE TITLE
Enabling normalization causes an error

### ISSUE THREAD

**Issue by eitanrich** [richzhang/PerceptualSimilarity#47]
It looks like `target` and `pred` should be replaced with `in0` and `in1`.
https://github.com/richzhang/PerceptualSimilarity/blob/a1188a38413555be7207b3565397e4c7cd51a4f7/lpips/lpips.py#L83

To reproduce: set `normalize=True` when calling the loss function.

**Comment by richzhang** [comment]
You're right, fixed. Thank you!!
