### ISSUE TITLE
'lpips' has no attribut 'PerceptualLoss'

### ISSUE THREAD

**Issue by jinzhenmu** [richzhang/PerceptualSimilarity#56]
> When i use the ' sudo pip3 install lpips'

- import lpips

- and   i use ' percept = lpips.PerceptualLoss(model='net-lin', net ='vgg', use_gpu= True)

- then the error  'lpips' has no attribut 'PerceptualLoss'

**Comment by richzhang** [comment]
I changed the API a bit. You can see the example files for the readme (https://github.com/richzhang/PerceptualSimilarity#quick-start) for the syntax. Sorry for any confusion.

**Comment by jinzhenmu** [comment]
Thank you.
