### ISSUE TITLE
Relation between scaling weights of paper and implementation

### ISSUE THREAD

**Issue by francois-rozet** [richzhang/PerceptualSimilarity#59]
Hello @richzhang,

In the LPIPS paper, the 1x1 scaling convolution of the difference of the activations is performed before the squaring.

![image](https://user-images.githubusercontent.com/37352336/104763283-eb8afd00-5765-11eb-8c1e-77f66f467c06.png)

But, in the [implementation](https://github.com/richzhang/PerceptualSimilarity/blob/05f4ec246e2ca8daecdab0684353f3f3c054122c/lpips/lpips.py#L92), the difference of the activations is first squared, and after scaled.

```python
diffs[kk] = (feats0[kk]-feats1[kk])**2
...
self.lin[kk](diffs[kk])
```

Is this a mistake ? If yes, in the paper or in the implementation ?

**Comment by richzhang** [comment]
Yes, the weights in the implementation correspond to w^2 in the paper

**Comment by francois-rozet** [comment]
Thanks! Therefore, if I am not mistaken, the convolution could even be performed after the averaging.

Like,

![formula](https://user-images.githubusercontent.com/37352336/104774799-93f58d00-5777-11eb-9656-55d687d12961.gif)

or even

![formula](https://user-images.githubusercontent.com/37352336/104774907-c1423b00-5777-11eb-9d56-88619e932b8b.gif)

**Comment by richzhang** [comment]
You cannot collapse the channel direction before multiplying by w (which is scaling each channel)

**Comment by francois-rozet** [comment]
Ah yes sure, my notation isn't very accurate. The norm and MSE should be *spatial* only.

**Comment by richzhang** [comment]
Great, yes that seems correct then! (also add a sum over channel direction, in front of w_l)

**Comment by francois-rozet** [comment]
> Great, yes that seems correct then! (also add a sum over channel direction, in front of w_l)

Oh my bad, I wanted to write a dot product and not an element wise product. 

![formula](https://user-images.githubusercontent.com/37352336/104776108-d28c4700-5779-11eb-8794-f4bf7caa0754.gif)

In fact, it means that we can drop the `nn.Conv2d` for a `nn.Linear`, with the same weights. It might also make the code a bit faster since the product is performed on only one channel vector.

**Comment by francois-rozet** [comment]
Thank you, you can close the issue 👍
