### ISSUE TITLE
The distance result changes when I run several times?

### ISSUE THREAD

**Issue by imerse** [richzhang/PerceptualSimilarity#60]
As the title,  I wonder does there have a random process in the flow ? Why the distance changes each time?
And does the forward process take more time on gpu than cpu? I test on v100 gpu with 402ms for the first pair and about 50ms on cpu. Looks strange! Any help will be appreciated! Thanks.

![image](https://user-images.githubusercontent.com/8415005/105043877-0bd9f500-5aa1-11eb-8fda-b15ee7b02835.png)

**Comment by richzhang** [comment]
Hmm, I'm a little confused wy it's loading a resnet18 model. Were you able to run the example command and get this?

![image](https://user-images.githubusercontent.com/18079594/105096988-bbd93f00-5a5c-11eb-80ec-7058de3a0d84.png)

**Comment by imerse** [comment]
Sorry, I misunderstood the location of the automatically downloaded model. Now the result of each inference is the same, but I still don't understand why the efficiency of running on GPU is not as good as on CPU.

**Comment by richzhang** [comment]
May be that communication dominates when running a single image. Try for a bigger batch of images and see if the trend still holds
