### ISSUE TITLE
How to remove the notification when using lpips

### ISSUE THREAD

**Issue by thunanguyen** [richzhang/PerceptualSimilarity#62]
I've tried to use lpips in my super-resolution project and it keeps printing: 
"Loading model from: C:\Workspace\envs\workplace\lib\site-packages\lpips\weights\v0.1\alex.pth
Setting up [LPIPS] perceptual loss: trunk [alex], v[0.1], spatial [off]"

Is there any way to turn it off?

**Comment by mago876** [comment]
You can set the 'verbose' flag to 'False': `loss_fn_alex = lpips.LPIPS(net='alex', verbose=False)`

**Comment by thunanguyen** [comment]
> You can set the 'verbose' flag to 'False': `loss_fn_alex = lpips.LPIPS(net='alex', verbose=False)`

thanks
