### ISSUE TITLE
Visualize which areas in the image contribute to the loss

### ISSUE THREAD

**Issue by gafniguy** [richzhang/PerceptualSimilarity#63]
Hi, 

Thanks for the paper and making it so accessible and easy to use. 

For pixel-aligned losses, it's easy to show which areas of the generated image are wrong, by doing e.g L1(generated, GT) pixel-wise and showing it as an image, resulting in some sort of error map.

What do you think would be a good way to get something like this for LPIPS? I would like to **see** which areas in the image contributed to higher LPIPS distance.

Thanks

**Comment by richzhang** [comment]
Hi, thanks for the question. Look at setting `spatial=True` here: https://github.com/richzhang/PerceptualSimilarity/blob/master/lpips/lpips.py#L23

**Comment by gafniguy** [comment]
Perfect, thank you so much.
