### ISSUE TITLE
LPIPS source comments are reversed?

### ISSUE THREAD

**Issue by torridgristle** [richzhang/PerceptualSimilarity#77]
At https://github.com/richzhang/PerceptualSimilarity/blob/ecfae6f09f9d3dddc17c88702174b7f78f9925c0/lpips/lpips.py#L52-L54 it seems like line 53 should be [False] and line 54 should be [True] since enabling it would enable grad, but the comment says that setting it to true would freeze it.

**Comment by richzhang** [comment]
Thanks, you're right, it was mixed up. I switched them: https://github.com/richzhang/PerceptualSimilarity/blob/master/lpips/lpips.py#L52.

**Comment by torridgristle** [comment]
It may be pedantic, but the order should probably be True, False in order to match the others. Personally I tend to expect patterns in things and I may assume the first one is true and the second is false even if it's explicitly labelled the other way around, and I reckon other folks could make that same mistake when glossing over it.

**Comment by richzhang** [comment]
Thanks, the default parameters are listed first
