### ISSUE TITLE
AttributeError: module 'lpips' has no attribute 'LPIPS'

### ISSUE THREAD

**Issue by zhangyahu1** [richzhang/PerceptualSimilarity#81]
Hi,

I try to calculate the lipis for two images, and run:

> import lpips
import torch
loss_fn_alex = lpips.LPIPS(model='net-lin', net='alex', use_gpu=use_gpu)

It raises the error:

> AttributeError: module 'lpips' has no attribute 'LPIPS'

**Comment by ssumin6** [comment]
How do you solve this problem?

**Comment by outfielder** [comment]
I am getting the same problem

**Comment by Mr-HF** [comment]
the promblme have who solved? i meet the promblem too
