### ISSUE TITLE
Wrong normalization?

### ISSUE THREAD

**Issue by lars76** [richzhang/PerceptualSimilarity#86]
Where does the mean/std come from in [ScalingLayer](https://github.com/richzhang/PerceptualSimilarity/blob/master/lpips/lpips.py#L147)? The VGG16 mean/std is mean = [0.485, 0.456, 0.406] and std = [0.229, 0.224, 0.225].

**Comment by 98mxr** [comment]
I have a small problem. Since it is to be compatible with imagenet's mean/std, it is not good to input the img of [0, 1] from the beginning.

**Comment by Zyriix** [comment]
Still confused about this.
If my inputs is already normalized by imagenet mean std.
Eg: x (0-1)
x = (x - imgnet_mean)/imgnet_val

if i do this before i put it into lpips , does it means that i can just delete the scaling layers?

**Comment by richzhang** [comment]
Yes, that's right

**Comment by Zyriix** [comment]
> Yes, that's right

ok, thank you : )
