### ISSUE TITLE
PNetlin.forward image normalization 

### ISSUE THREAD

**Issue by roimehrez** [richzhang/PerceptualSimilarity#9]
```
    def forward(self, in0, in1):
        in0_sc = (in0 - self.shift.expand_as(in0)) / self.scale.expand_as(in0)
        in1_sc = (in1 - self.shift.expand_as(in0)) / self.scale.expand_as(in0)

        if (self.pnet_tune):
            outs0 = self.net.forward(in0)
            outs1 = self.net.forward(in1)
        else:
            outs0 = self.net[0].forward(in0)
            outs1 = self.net[0].forward(in1)
```

Why you don't use `in0_sc ` to feed the net? Is it a bug or a feature?

**Comment by richzhang** [comment]
That is a bug! Thank you for the catch! I am re-running the experiments right now. The results do not change much. I'll fix the bug and release new weights.

In the meantime, you can fix the bug and retrain yourself [train_test_metric.sh](train_test_metric.sh) as well.
